### ISSUE TITLE
Pine A64-LTS support

### ISSUE THREAD

**Issue by invadrew** [swkim01/RPi.GPIO-PineA64#12]
Does it work on Pine A64-LTS? When i'm type in python3 prompt `>>> import RPi.GPIO` i got 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!`

**Comment by BlackMage2** [comment]
what is the difference between Pine A64 and Pine A64-LTS? how can i access the PI-2-Bus and the Euler bus and the exp io bus with the Pine A64 board with this RPi.GPIO-PineA64 lib ?
